version: "3.8"

services:
  todo-postgres:
    image: postgres:${IMAGE}
    container_name: todo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo